CREATE TABLE PRODUTO_CATEGORIA(
    CATEGORIA_ID INTEGER NOT NULL,
    PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(ID),
    FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTO(ID)
);